import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      license : 'Text License for  30d',
      acountNumber: 'Ecovoy-61100 TEXT 30D 2021/2/2 TEXT 30D',
      nickName : 'GOED2854525',
      name: 'Edgar',
      email: 'edgar.gonzalez@qragile.uy',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isDelivery: true,
      isSeller: true,
      isAct: true,
      seller: {
        name: 'VoltBike',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
      delivery: {
        shipping  : '4040404040',
      },
    },
    {
        license : 'Text License for  30d',
        acountNumber: 'Ecovoy-61100 TEXT 30D 2021/2/2 TEXT 30D',
        nickName : 'JSANZIPAR',
        name: 'Jaime',
        email: 'jaime@qragile.uy',
        password: bcrypt.hashSync('1234', 8),
        isAdmin: true,
        isDelivery: true,
        isSeller: true,
        isAct: true,
    },
    {
      License:' estee ',
      acountNumber: 'Ecovoy-61100 TEXT 30D 2021/2/2 TEXT 30D',
      nickName : 'text1',
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      license : 'Text License for  30d',
      acountNumber: 'Ecovoy-61100 TEXT 30D 2021/2/2 TEXT 30D',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      license : "Text License for  30d",
      acountNumber: 'Ecovoy-61100 TEXT 30D 2021/2/2 TEXT 30D',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      license : 'Text License for  30d',
      acountNumber: 'Ecovoy-61100 TEXT 30D 2021/2/2 TEXT 30D',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      license : 'Text License for  30d',
      acountNumber: 'Ecovoy-61100 TEXT 30D 2021/2/2 TEXT 30D',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      license : 'Text License for  30d',
      acountNumber: 'Ecovoy-61100 TEXT 30D 2021/2/2 TEXT 30D',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      license : 'Text License for  30d',
      acountNumber: 'Ecovoy-61100 TEXT 30D 2021/2/2 TEXT 30D',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
