export const DELIVERY_CREATE_REQUEST = 'DELIVERY_CREATE_REQUEST';
export const DELIVERY_CREATE_SUCCESS = 'DELIVERY_CREATE_SUCCESS';
export const DELIVERY_CREATE_FAIL = 'DELIVERY_CREATE_FAIL';
export const DELIVERY_CREATE_RESET = 'DELIVERY_CREATE_RESET';

export const DELIVERY_PAY_REQUEST = 'DELIVERY_PAY_REQUEST';
export const DELIVERY_PAY_SUCCESS = 'DELIVERY_PAY_SUCCESS';
export const DELIVERY_PAY_FAIL = 'DELIVERY_PAY_FAIL';
export const DELIVERY_PAY_RESET = 'DELIVERY_PAY_RESET';

export const DELIVERY_DELIVER_REQUEST = 'DELIVERY_DELIVER_REQUEST';
export const DELIVERY_DELIVER_SUCCESS = 'DELIVERY_DELIVER_SUCCESS';
export const DELIVERY_DELIVER_FAIL = 'DELIVERY_DELIVER_FAIL';
export const DELIVERY_DELIVER_RESET = 'DELIVERY_DELIVER_RESET';

export const DELIVERY_DETAILS_REQUEST = 'DELIVERY_DETAILS_REQUEST';
export const DELIVERY_DETAILS_SUCCESS = 'DELIVERY_DETAILS_SUCCESS';
export const DELIVERY_DETAILS_FAIL = 'DELIVERY_DETAILS_FAIL';

export const DELIVERY_MINE_LIST_REQUEST = 'DELIVERY_MINE_LIST_REQUEST';
export const DELIVERY_MINE_LIST_SUCCESS = 'DELIVERY_MINE_LIST_SUCCESS';
export const DELIVERY_MINE_LIST_FAIL = 'DELIVERY_MINE_LIST_FAIL';

export const DELIVERY_LIST_REQUEST = 'DELIVERY_LIST_REQUEST';
export const DELIVERY_LIST_SUCCESS = 'DELIVERY_LIST_SUCCESS';
export const DELIVERY_LIST_FAIL = 'DELIVERY_LIST_FAIL';

export const DELIVERY_DELETE_REQUEST = 'DELIVERY_DELETE_REQUEST';
export const DELIVERY_DELETE_SUCCESS = 'DELIVERY_DELETE_SUCCESS';
export const DELIVERY_DELETE_FAIL = 'DELIVERY_DELETE_FAIL';
export const DELIVERY_DELETE_RESET = 'DELIVERY_DELETE_RESET';

export const DELIVERY_SUMMARY_REQUEST = 'DELIVERY_SUMMARY_REQUEST';
export const DELIVERY_SUMMARY_SUCCESS = 'DELIVERY_SUMMARY_SUCCESS';
export const DELIVERY_SUMMARY_FAIL = 'DELIVERY_SUMMARY_FAIL';
