
export const SCANNER_CREATE_REQUEST = 'SCANNER_CREATE_REQUEST';
export const SCANNER_CREATE_SUCCESS = 'SCANNER_CREATE_SUCCESS';
export const SCANNER_CREATE_FAIL = 'SCANNER_CREATE_FAIL';
export const SCANNER_CREATE_RESET = 'SCANNER_CREATE_RESET';

export const SCANNER_LIST_REQUEST = 'SCANNER_LIST_REQUEST';
export const SCANNER_LIST_SUCCESS = 'SCANNER_LIST_SUCCESS';
export const SCANNER_LIST_FAIL = 'SCANNER_LIST_FAIL';

export const SCANNER_DELETE_REQUEST = 'SCANNER_DELETE_REQUEST';
export const SCANNER_DELETE_SUCCESS = 'SCANNER_DELETE_SUCCESS';
export const SCANNER_DELETE_FAIL = 'SCANNER_DELETE_FAIL';
export const SCANNER_DELETE_RESET = 'SCANNER_DELETE_RESET';

export const SCANNER_EMPTY = 'SCANNER_EMPTY';